import{a as p,S as m,i as a}from"./assets/vendor-BGjKfUOh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const h="53452930-453d1b75f98a5875cf6a66d5c";function g(i){return p("https://pixabay.com/api/",{params:{key:h,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0}})}const c=document.querySelector(".gallery"),l=document.querySelector(".loader"),y=new m(".gallery a",{captionsData:"alt",captionDelay:250});function b(i){const r=i.map(({webformatURL:o,largeImageURL:n,tags:e,likes:t,views:s,comments:u,downloads:d})=>`<li class="gallery-item">
      <a class="big-img" href="${n}"><img src="${o}" alt="${e}" width="360px" height="152px" /></a>
      <div class="info">
      <p class="info-descr"><b>Likes:</b> ${t}</p>
      <p class="info-descr"><b>Views:</b> ${s}</p>
      <p class="info-descr"><b>Comments:</b> ${u}</p>
      <p class="info-descr"><b>Downloads:</b> ${d}</p>
      </div>
      </li>`).join("");c.innerHTML=r,y.refresh()}function L(){c.innerHTML=""}function S(){l.hidden=!1}function f(){l.hidden=!0}const w=document.querySelector(".form"),$=document.querySelector(".form-input");w.addEventListener("submit",q);f();function q(i){i.preventDefault();const r=$.value.trim();r&&(L(),S(),g(r).then(o=>{o.data.hits.length===0?a.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"}):b(o.data.hits)}).catch(o=>{a.show({message:`${o}`,position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"})}).finally(()=>f()))}
//# sourceMappingURL=index.js.map
