import{S as f,a as d,i as p}from"./assets/vendor-BGjKfUOh.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const a=document.querySelector(".gallery"),c=document.querySelector(".loader"),m=new f(".gallery a",{captionsData:"alt",captionDelay:250});function h(i){const o=i.map(({webformatURL:r,largeImageURL:n,tags:e,likes:t,views:s,comments:l,downloads:u})=>`<li class="gallery-item">
      <a class="big-img" href="${n}"><img src="${r}" alt="${e}" width="360px" height="152px" /></a>
      <div class="info">
      <p class="info-descr"><b>Likes:</b> ${t}</p>
      <p class="info-descr"><b>Views:</b> ${s}</p>
      <p class="info-descr"><b>Comments:</b> ${l}</p>
      <p class="info-descr"><b>Downloads:</b> ${u}</p>
      </div>
      </li>`).join("");a.innerHTML=o,m.refresh()}function y(){a.innerHTML=""}function g(){c.hidden=!1}function b(){c.hidden=!0}const L="53452930-453d1b75f98a5875cf6a66d5c";function S(i){return d("https://pixabay.com/api/",{params:{key:L,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0}})}const q=document.querySelector(".form"),v=document.querySelector(".form-input");q.addEventListener("submit",w);function w(i){i.preventDefault();const o=v.value;y(),g(),S(o).then(r=>{r.data.hits.length===0?p.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"}):h(r.data.hits)}).catch(r=>console.log(r)).finally(()=>b())}
//# sourceMappingURL=index.js.map
